# Generated by Django 4.1 on 2023-05-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnjoyKidsNumbers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member_number', models.CharField(max_length=8)),
                ('head_number', models.CharField(max_length=8)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('price_plan_id', models.CharField(blank=True, max_length=255, null=True)),
                ('price_plan_name', models.CharField(blank=True, max_length=255, null=True)),
                ('price_plan_code', models.CharField(blank=True, max_length=255, null=True)),
                ('exp_date', models.DateTimeField()),
                ('eff_date', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'db_table': 'enjoy_kids_numbers',
                'managed': False,
            },
        ),
    ]
